#! /usr/bin/env python3

import sys, os
from time import gmtime, strftime

def usage():

	opts = {
		"-t, --time": "include hours and minutes",
	}

	size = len(max(opts, key=lambda key: len(key)))

	print("Add a timestamp into the file name(s).",
		  "Usage: " + os.path.basename(__file__) + " [OPTION] FILE1 [FILE2 ...]",
		  sep='\n')

	for record in opts:
		  print(("  {0:" + str(size + 2) + "s}{1:s}").format(record, opts[record]))

def main():
	if len(sys.argv) == 1:
		usage()
		return 1

	if len(sys.argv) == 2 and (sys.argv[1] == "-h" or sys.argv[1] == "--help"):
			usage()
			return 0

	if (sys.argv[1] == "-t" or sys.argv[1] == "--time"):
		if len(sys.argv) == 2:
			usage()
			return 1
		time = strftime("%Y-%m-%d_%H-%M", gmtime())
		sys.argv.pop(1)
	else:
		time = strftime("%Y-%m-%d", gmtime())

	ret = 0

	for file in sys.argv[1:]:
		if not os.path.exists(file):
			print("File " + "'" + file + "'" + " does not exist.", file=sys.stderr)
			ret = 1
			continue
		name, ext = os.path.splitext(file)
		if ext and len(ext) <= 8:
			os.rename(file, name + "_[" + time + "]" + ext)
		else:
			os.rename(file, file + "_[" + time + "]")

ret = main()
sys.exit(ret)
